version: '3.1'

services:
  iot:
    container_name: iot
    build: .
    env_file:
      - .env
    ports:
      - 7000:7000
    environment:
      - PORT=7000
      - TIME_ZONE=Africa/Lagos
    volumes:
      - ./:/go/src/github.com/IamNator/iot